server:
  port: 8401
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enable: true
ribbon:
  ConnectionTimeout: 3000 #服务器请求连接超时时间
  ReadTimeout: 3000  #服务请求处理超时时间